### ISSUE TITLE
missing module ?

### ISSUE THREAD

**Issue by abdulAttya** [KHLALA-Gh/grub-themes-manager#1]
```python 
from lib.check_packages import is_package_installed 
```

throws an error :
`Traceback (most recent call last):
  File "/home/ibnattya/Downloads/builds/grub-themes-manager/install.py", line 6, in <module>
    from lib.check_packages import is_package_installed
ModuleNotFoundError: No module named 'lib.check_packages'`

**Comment by KHLALA-Gh** [comment]
Thank you for submitting this issue.
it seems that i forgot to remove line 6 in the file [install.py](../blob/main/install.py) after deleting the `check_packages` library.
The bug is fixed in this commit 970e074
