### ISSUE TITLE
externally-managed-environment PEP 668 breaking the install on debian

### ISSUE THREAD

**Issue by lpako** [KHLALA-Gh/grub-themes-manager#3]
using debian 12 installed pip python3 and get an error because PEP 668 is making the python externally managed 

 This environment is externally managed 
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
bash: charset-normalizer==3.3.2: command not found

**Comment by lpako** [comment]
venv was installed and still gave me the error

**Comment by lpako** [comment]
i think its because the python command doesn't in install.sh work only python3 works i don't know python really well

**Comment by lpako** [comment]
yes i fixed it there was an error in the install.sh script i changed python -m venv $ENVDIR to python3 -m venv $ENVDIR and everything works and installs well

**Comment by lpako** [comment]
and the .bashrc file is very glitchy i installed it on my /home/user bashrc its just very confusing for me i dont know what to do when i type in grub-tm it says it doesnt exist

**Comment by KHLALA-Gh** [comment]
I'm so sorry for not responding, I've been inactive for about a month in this repo. If you have any problems feel free to ask.
